import { Inter, Dancing_Script, Rubik } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

import "./globals.css";
import Navbar from "./_navbar/Navbar";

import StoreContextProvider from "./context/Context";

const inter = Rubik({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <StoreContextProvider>{children}</StoreContextProvider>
      </body>
    </html>
  );
}
